[package]
name = "transr"
version = "0.2.2"
edition = "2021"
description = "A Cli to update xml content from csv"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "4"
csv = "1.3.0"
glob = "0.3.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
